# DEV

# App
server.port: 8010

# MariaDB
mariadb: gorest:gorest_pdw@tcp(localhost:3306)/gorest_adm

# MongoDB
mongodb: mongodb://gorest:gorest_pdw@localhost:27017/admin?connectTimeoutMS=1000&serverSelectionTimeoutMS=1000&socketTimeoutMS=1500