version: '3.1'

services:
  gorest-mariadb:
    image: "mariadb:10.4-bionic"
    ports :
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: gorest_pdw
      MYSQL_DATABASE: gorest_adm
      MYSQL_USER: gorest
      MYSQL_PASSWORD: gorest_pdw
    volumes:
      - ~/.gorest-mariadb:/var/lib/mysql
    restart: on-failure