version: '3.1'

services:
  gorest-mongodb:
    image: "mongo:3.7-jessie"
    ports :
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: gorest
      MONGO_INITDB_ROOT_PASSWORD: gorest_pdw
    command: --auth 
    restart: on-failure