version: '3.1'

services:
  latanton-mongodb:
    image: "mongo:3.7-jessie"
    ports :
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: latanton
      MONGO_INITDB_ROOT_PASSWORD: latanton_pdw
    command: --auth 
    restart: on-failure